script: rake ci
rvm:
  - 1.9.3
  - ruby-head
  - jruby-19mode

# Getting a deadlock in the nonblocking connect code :(
#  - jruby-head

# See https://github.com/rubinius/rubinius/issues/1611
#  - rbx-19mode

notifications:
  irc: "irc.freenode.org#celluloid"
